# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=tbd
#      - MONGO_INITDB_ROOT_PASSWORD=tbd
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: